title: Huong (Jenny) Nguyen

logo: "/images/photo.png?raw=true" 

description: > 
  <p align="center">
  Data Junkie
  <br><br>
  <a href="https://www.linkedin.com/in/huong-jenny-nguyen/">LinkedIn</a> |
  <a href="https://github.com/jennynguyen-97">GitHub</a>
  <p align="justify">
  I am pursing a Master degree in Business Analytics at the Fuqua School of Business, Duke University. I have 2+ years of work experience in Accounting/Finance where I delivered value-based and data-driven insights to companies to enhance profits and improve internal controls. Upon graduation, I hope to implement my technical skills in Data Science with my business background to translate data into meaningful impacts to companies.
  <br>  <br>
  I love applying Machine Learning Algorithms to deliver actionable insights to Healthcare and Tech industries.
  <br><br>
  
  </p>
theme: jekyll-theme-minimal
