title: Huong (Jenny) Nguyen

logo: "/images/photo.png?raw=true" 

description: > 
  <p align="center">
  Data Junkie
  <br><br>
  <a href="https://www.linkedin.com/in/huong-jenny-nguyen">LinkedIn</a> |
  <a href="https://github.com/jennynguyen-97">GitHub</a>
  <p align="justify">
  I am pursing a Master degree in Business Analytics at the Fuqua School of Business, Duke University. 
  <br>  <br>
  I hope to complement my business background with my technical skills in Data Science to translate data into meaningful impacts to companies.
  <br><br>
  
  </p>
theme: jekyll-theme-minimal
